/*
 * DO NOT MODIFY.
 * This file was generated by ms_gen_mvxv_h.py
 */
#define MVXV_HEAD_VER   "2"
#define MVXV_LIB_TYPE   "##"
#define MVXV_CHIP_ID    "I6"
#define MVXV_CHANGELIST "g615d18d"
#define MVXV_COMP_ID    "KL_LX409####"
#define MVXV_EXT        "[BR:stable_i6_ipc]"

