EXTRA_CFLAGS += -Idrivers/sstar/include
EXTRA_CFLAGS += -Idrivers/sstar/fsp_qspi/drv/inc
EXTRA_CFLAGS += -Idrivers/sstar/fsp_qspi/hal/inc
EXTRA_CFLAGS += -Iinclude/linux
obj-y += hal/src/halFSP_QSPI.o
obj-y += drv/src/drvFSP_QSPI.o
