CONFIG_SSTAR_CHIP_NAME := $(subst ",,$(CONFIG_SSTAR_CHIP_NAME))
EXTRA_CFLAGS += -Idrivers/sstar/include
EXTRA_CFLAGS      += -Idrivers/sstar/include/$(CONFIG_SSTAR_CHIP_NAME)

obj-y += voltage_ctrl.o
